/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

type RedisExpansion interface{}

type TenantExpansion interface{}
