/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// RedisListerExpansion allows custom methods to be added to
// RedisLister.
type RedisListerExpansion interface{}

// RedisNamespaceListerExpansion allows custom methods to be added to
// RedisNamespaceLister.
type RedisNamespaceListerExpansion interface{}

// TenantListerExpansion allows custom methods to be added to
// TenantLister.
type TenantListerExpansion interface{}
