/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated clientset.
package versioned
