/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	demov1 "github.com/lichuan0620/k8s-controller-the-hard-way/pkg/kubernetes/apis/demo/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedises implements RedisInterface
type FakeRedises struct {
	Fake *FakeDemoV1
	ns   string
}

var redisesResource = schema.GroupVersionResource{Group: "demo.lichuan.guru", Version: "v1", Resource: "redises"}

var redisesKind = schema.GroupVersionKind{Group: "demo.lichuan.guru", Version: "v1", Kind: "Redis"}

// Get takes name of the redis, and returns the corresponding redis object, and an error if there is any.
func (c *FakeRedises) Get(ctx context.Context, name string, options v1.GetOptions) (result *demov1.Redis, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redisesResource, c.ns, name), &demov1.Redis{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Redis), err
}

// List takes label and field selectors, and returns the list of Redises that match those selectors.
func (c *FakeRedises) List(ctx context.Context, opts v1.ListOptions) (result *demov1.RedisList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redisesResource, redisesKind, c.ns, opts), &demov1.RedisList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &demov1.RedisList{ListMeta: obj.(*demov1.RedisList).ListMeta}
	for _, item := range obj.(*demov1.RedisList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redises.
func (c *FakeRedises) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redisesResource, c.ns, opts))

}

// Create takes the representation of a redis and creates it.  Returns the server's representation of the redis, and an error, if there is any.
func (c *FakeRedises) Create(ctx context.Context, redis *demov1.Redis, opts v1.CreateOptions) (result *demov1.Redis, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redisesResource, c.ns, redis), &demov1.Redis{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Redis), err
}

// Update takes the representation of a redis and updates it. Returns the server's representation of the redis, and an error, if there is any.
func (c *FakeRedises) Update(ctx context.Context, redis *demov1.Redis, opts v1.UpdateOptions) (result *demov1.Redis, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redisesResource, c.ns, redis), &demov1.Redis{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Redis), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRedises) UpdateStatus(ctx context.Context, redis *demov1.Redis, opts v1.UpdateOptions) (*demov1.Redis, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(redisesResource, "status", c.ns, redis), &demov1.Redis{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Redis), err
}

// Delete takes name of the redis and deletes it. Returns an error if one occurs.
func (c *FakeRedises) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(redisesResource, c.ns, name, opts), &demov1.Redis{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedises) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redisesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &demov1.RedisList{})
	return err
}

// Patch applies the patch and returns the patched redis.
func (c *FakeRedises) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *demov1.Redis, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redisesResource, c.ns, name, pt, data, subresources...), &demov1.Redis{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Redis), err
}
