/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/lichuan0620/k8s-controller-the-hard-way/pkg/kubernetes/client/clientset/versioned/typed/demo/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDemoV1 struct {
	*testing.Fake
}

func (c *FakeDemoV1) Redises(namespace string) v1.RedisInterface {
	return &FakeRedises{c, namespace}
}

func (c *FakeDemoV1) Tenants() v1.TenantInterface {
	return &FakeTenants{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDemoV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
