/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	demov1 "github.com/lichuan0620/k8s-controller-the-hard-way/pkg/kubernetes/apis/demo/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTenants implements TenantInterface
type FakeTenants struct {
	Fake *FakeDemoV1
}

var tenantsResource = schema.GroupVersionResource{Group: "demo.lichuan.guru", Version: "v1", Resource: "tenants"}

var tenantsKind = schema.GroupVersionKind{Group: "demo.lichuan.guru", Version: "v1", Kind: "Tenant"}

// Get takes name of the tenant, and returns the corresponding tenant object, and an error if there is any.
func (c *FakeTenants) Get(ctx context.Context, name string, options v1.GetOptions) (result *demov1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tenantsResource, name), &demov1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Tenant), err
}

// List takes label and field selectors, and returns the list of Tenants that match those selectors.
func (c *FakeTenants) List(ctx context.Context, opts v1.ListOptions) (result *demov1.TenantList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tenantsResource, tenantsKind, opts), &demov1.TenantList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &demov1.TenantList{ListMeta: obj.(*demov1.TenantList).ListMeta}
	for _, item := range obj.(*demov1.TenantList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tenants.
func (c *FakeTenants) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tenantsResource, opts))
}

// Create takes the representation of a tenant and creates it.  Returns the server's representation of the tenant, and an error, if there is any.
func (c *FakeTenants) Create(ctx context.Context, tenant *demov1.Tenant, opts v1.CreateOptions) (result *demov1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tenantsResource, tenant), &demov1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Tenant), err
}

// Update takes the representation of a tenant and updates it. Returns the server's representation of the tenant, and an error, if there is any.
func (c *FakeTenants) Update(ctx context.Context, tenant *demov1.Tenant, opts v1.UpdateOptions) (result *demov1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tenantsResource, tenant), &demov1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Tenant), err
}

// Delete takes name of the tenant and deletes it. Returns an error if one occurs.
func (c *FakeTenants) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(tenantsResource, name, opts), &demov1.Tenant{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTenants) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tenantsResource, listOpts)

	_, err := c.Fake.Invokes(action, &demov1.TenantList{})
	return err
}

// Patch applies the patch and returns the patched tenant.
func (c *FakeTenants) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *demov1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tenantsResource, name, pt, data, subresources...), &demov1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.Tenant), err
}
