/*
k8s-controller-the-hard-way, a guide to really, really understand how to program k8s controllers
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/lichuan0620/k8s-controller-the-hard-way/pkg/kubernetes/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Redises returns a RedisInformer.
	Redises() RedisInformer
	// Tenants returns a TenantInformer.
	Tenants() TenantInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Redises returns a RedisInformer.
func (v *version) Redises() RedisInformer {
	return &redisInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Tenants returns a TenantInformer.
func (v *version) Tenants() TenantInformer {
	return &tenantInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
